name: "Minimal AWS SAM Cli Github Action"
description: "Run AWS SAM commands via Github Actions"
author: "smurphnturf"
branding:
  icon: "terminal"
  color: "blue"
inputs:
  directory:
    description: "directory in which to execute sam command."
    default: "./"
  build:
    description: "Run sam build and npm install on sub directory layers before sam command."
    default: "true"
runs:
  using: "docker"
  image: "./Dockerfile"